parameters:
    that_moneybird.redirect_url: ''
    that_moneybird.client_id: ''
    that_moneybird.client_secret: ''
    that_moneybird.debug: ''

services:
    that_moneybird.connection:
        class: 'Picqer\Financials\Moneybird\Connection'
        public: false
        calls:
            - [setClientId, ['%that_moneybird.client_id%']]
            - [setClientSecret, ['%that_moneybird.client_secret%']]
            - [setRedirectUrl, ['%that_moneybird.redirect_url%']]
            - [setTesting, ['%that_moneybird.debug%']]
       
    that_moneybird.code_fetcher:
        class: 'Thatside\MoneybirdBundle\Services\ThatMoneybirdCodeFetcherDummyService'
                   
    that_moneybird:
        class: 'Thatside\MoneybirdBundle\Services\ThatMoneybirdService'
        arguments: 
          - '@that_moneybird.connection'
          - '@that_moneybird.code_fetcher'
          