language: php

php:
  - 5.6
  - 7.1

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.3.*

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-dist
  - composer install --prefer-dist

script: vendor/bin/phpunit

notifications:
  email: harammin@gmail.com

